#!/bin/sh

NAME=$(basename $0)

DATADIR=${HOME}/Data/mysql
BASEDIR=$(brew --prefix mysql)
COMMAND='mysql.server'
USER=$(whoami)

case "${1}" in
start)
  $COMMAND start --basedir="${BASEDIR}" --user="${USER}" --datadir="${DATADIR}" --tmpdir=/tmp
  ;;
stop)
  $COMMAND stop --basedir="${BASEDIR}" --user="${USER}" --datadir="${DATADIR}" --tmpdir=/tmp
  ;;
status)
  $COMMAND status
  ;;
*)
  echo "usage: ${NAME} { start | stop | status }" > /dev/stderr
  exit 64
  ;;
esac

exit 0
